---
name: Push to main

'on':
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - README.md

jobs:

  build:
    name: Build
    uses: ./.github/workflows/build.yml

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Publish npm package
        uses: sknups/publish-npm-package@v1
        with:
          service-account-key-json: ${{ secrets.GCP_DEV_DRM_SA_KEY }}
