---
name: Push to branch

'on':
  push:
    branches:
      - '*'
      - '!main'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:

  build:

    name: Build
    runs-on: ubuntu-22.04

    permissions:
      contents: 'read'
      id-token: 'write'

    timeout-minutes: 5

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Execute YAMLlint
        uses: ibiqlik/action-yamllint@v3

      - name: Build JavaScript project
        uses: sknups/sknups-build-javascript-action@v1
        with:
          skip_lint: true
          skip_test: true
